### ISSUE TITLE
[ERROR] Failed to execute goal on project exotic-server

### ISSUE THREAD

**Issue by xanren7716** [platonai/exotic#13]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ exotic-services ---
[INFO] Installing C:\Program Files\Java\apache-maven-3.8.7\exotic\exotic-services\target\exotic-services-1.11.4-SNAPSHOT.jar to C:\Users\缁啓瀹岀編\.m2\repository\ai\platon\exotic\exotic-services\1.11.4-SNAPSHOT\exotic-services-1.11.4-SNAPSHOT.jar
[INFO] Installing C:\Program Files\Java\apache-maven-3.8.7\exotic\exotic-services\pom.xml to C:\Users\缁啓瀹岀編\.m2\repository\ai\platon\exotic\exotic-services\1.11.4-SNAPSHOT\exotic-services-1.11.4-SNAPSHOT.pom
[INFO]
[INFO] -------------------< ai.platon.exotic:exotic-server >-------------------
[INFO] Building Exotic Server 1.11.4-SNAPSHOT                            [4/10]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for ai.platon.scent:scent-boot:jar:1.10.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for ai.platon.scent:scent-rest:jar:1.10.3-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Exotic 1.11.4-SNAPSHOT:
[INFO]
[INFO] Exotic ............................................. SUCCESS [  1.450 s]
[INFO] Exotic Driver ...................................... SUCCESS [02:53 min]
[INFO] Exotic Services .................................... SUCCESS [ 39.033 s]
[INFO] Exotic Server ...................................... FAILURE [  0.708 s]
[INFO] Exotic Standalone .................................. SKIPPED
[INFO] Exotic App ......................................... SKIPPED
[INFO] Exotic Examples .................................... SKIPPED
[INFO] Exotic ML Examples ................................. SKIPPED
[INFO] Exotic RPA Examples ................................ SKIPPED
[INFO] Exotic OCR Examples ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:35 min
[INFO] Finished at: 2023-01-01T12:13:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project exotic-server: Could not resolve dependencies for project ai.platon.exotic:exotic-server:jar:1.11.4-SNAPSHOT: The following artifacts could not be resolved: ai.platon.scent:scent-boot:jar:1.10.3-SNAPSHOT, ai.platon.scent:scent-rest:jar:1.10.3-SNAPSHOT: ai.platon.scent:scent-boot:jar:1.10.3-SNAPSHOT was not found in https://repo1.maven.org/maven2/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of Central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :exotic-server

**Comment by galaxyeye** [comment]
Add the following lines to your .m2/settings.xml.

```
<mirrors>
    <mirror>
        <id>maven-default-http-blocker</id>
        <mirrorOf>dummy</mirrorOf>
        <name>Dummy mirror to override default blocking mirror that blocks http</name>
        <url>http://0.0.0.0/</url>
    </mirror>
</mirrors>
```

As mentioned in the document: https://github.com/platonai/exotic#build-from-source

Good luck!

**Comment by rktdencxukw** [comment]
even added dummy mirror, still got the same error. it seems you guys forget to publish some code,  like 'ai.platon.scent.boot.autoconfigure.ScentContextInitializer', I only see import, but not source in whole github & gitee. 
`
[ERROR] Failed to execute goal on project exotic-server: Could not resolve dependencies for project ai.platon.exotic:exotic-server:jar:1.11.4-SNAPSHOT: The following artifacts could not be resolved: ai.platon.scent:scent-boot:jar:1.10.3-SNAPSHOT, ai.platon.scent:scent-rest:jar:1.10.3-SNAPSHOT: Failure to find ai.platon.scent:scent-boot:jar:1.10.3-SNAPSHOT in https://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of Central has elapsed or updates are forced -> [Help 1]
`

**Comment by rktdencxukw** [comment]
> even added dummy mirror, still got the same error. it seems you guys forget to publish some code, like 'ai.platon.scent.boot.autoconfigure.ScentContextInitializer', I only see import, but not source in whole github & gitee. `[ERROR] Failed to execute goal on project exotic-server: Could not resolve dependencies for project ai.platon.exotic:exotic-server:jar:1.11.4-SNAPSHOT: The following artifacts could not be resolved: ai.platon.scent:scent-boot:jar:1.10.3-SNAPSHOT, ai.platon.scent:scent-rest:jar:1.10.3-SNAPSHOT: Failure to find ai.platon.scent:scent-boot:jar:1.10.3-SNAPSHOT in https://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of Central has elapsed or updates are forced -> [Help 1]`

fixed the error. http://static.platonic.fun/repo/ai/platon/scent/scent-boot/ has 1.10.4 version, but no 1.10.3-SNAPSHOT version.

**Comment by platonai** [comment]
Great! But I still recommend you to pull the latest version on main branch, I have just upgraded two dependencies.

The new version fixes the problem that chrome 111 doesn't work.
